### ISSUE TITLE
Could not find component or interface MuraFW1.Application

### ISSUE THREAD

**Issue by jpresley** [stevewithington/MuraFW1#21]
Installation of FW1 plugin into fresh install of Mura 6.1.5727 cause the public side to throw the following error "Could not find the ColdFusion component or interface MuraFW1.Application."

Installation is on x64 Windows 7, ColdFusion 10, MSSQL, site is installed as a virtual directory under the Default Website in IIS.  Installation was clean without any errors and Mura functions as expected otherwise except when installing the plugin.

![fw1error](https://f.cloud.github.com/assets/1068916/2023605/f77835f8-885d-11e3-8b45-d1fd797c5e49.PNG)

**Comment by gpearson** [comment]
I am also getting this same error message now. I have reverted all of my files since last checkin to respository for this plugin. 

The context line of my settings.ini.cfm is context=

The /plugins/mappings.cfm file shows
`<cfset this.mappings["/MuraAuctions"] = pluginDir & "MuraAuctions`>



However if I change the plugin name to something NEW never used, the plugin will install without any issues.
