### ISSUE TITLE
How To: Subsystem Render Theme

### ISSUE THREAD

**Issue by dbudde** [stevewithington/MuraFW1#43]
Is it possible to have a subsystem render a theme?  We are wanting to develop a plugin that has an admin section and a public section that will render the front end theme.  Thanks.

**Comment by stevewithington** [comment]
@dbudde I'm not entirely sure I understand your question. 

If you simply want to access the assigned theme of a particular site, you can access it via `$.siteConfig('theme')`.

That said, FW/1 has its own way of handling layouts:

* If you want to control the layout for your entire plugin, you can edit the file under https://github.com/stevewithington/MuraFW1/blob/develop/common/layouts/default.cfm

* If you want to control layouts for the "admin" section of your plugin, you can edit files located under https://github.com/stevewithington/MuraFW1/tree/develop/admin/layouts

**Do you mean you want the plugin to be able to know which layout has been assigned?**
Because, if so, Mura plugins are rendered essentially as display objects, they can be assigned to any of the pre-defined display regions, and/or also explicitly output in a specific section of a theme's layout itself via code.

Something else to keep in mind is, as Mura receives a request for a specific page via the URL (e.g, domain.com/some/page/), once the requested URL has been verified, and a content item located, among other things, it checks to see if that specific content item has an assigned layout template. If so, then it uses it. If not, it traverses up the chain looking for alternate layout templates, etc. that may have been assigned by a parent, grandparent, etc. Assuming a valid layout template has been located, (and if not, it will look for default.cfm), the layout template then gets parsed. Remember, your plugin may be assigned to more than one region of the layout! So, as it's being parsed, your plugin may be invoked more than once.

In a way, it sounds like you're trying to turn this inside out...or, maybe you're trying to use Mura as a headless CMS? If so, you can do that, but it's well beyond the scope of a simple answer at this point.

**Comment by dbudde** [comment]
I have used FW/1 on it's own fairly extensively, so I understand how FW/1 handles layouts.  I have downloaded the Mura FW/1 plugin to start as my base and I just installed it with the 'admin' and 'app1' directories and none of the other 'appX' directories.

I can navigate to 'http://mySite.net/plugins/myPlugin/index.cfm/admin:main' and I can see the Mura Admin rendered with all the menus and such.  When I look inside of '/plugins/myPlugin/admin/layouts/default.cfm', I am able to see how the rendering is accomplished.
`application.pluginManager.renderAdminTemplate(body=local.body, pageTitle=rc.pc.getName(), compactDisplay=rc.compactDisplay)`

Now, when I navigate to 'http://mySite.net/plugins/myPlugin/index.cfm/app1:main', I see the content from '/plugins/myPlugins/app1/views/main/default.cfm' being rendered, but it is just on a white page.  It appears to be rendering inside of the layout from  '/plugins/myPlugins/common/layouts/default.cfm'.  So, my question is, how do I render the View inside of the Mura Theme?  I wish to render the View inside of the Mura Theme by processing the Mura Theme inside of the Layout that the View is being rendered in.

Does this clarify what I wish to do?

On a side note, I think of plugins as like a self-contained application that you can install into Mura.  The plugin itself does not necessarily get represented with a display object and it can be represented by multiple display objects.  I think display objects do fit your description above, but plugins can do much more than a display object.  They can contain mappings, custom tags, event handlers, display objects, class extensions, etc...

I would not comment on this normally, but just in case this gets read by someone else I wanted some followup clarification.  If I am wrong in my thinking, please feel free to correct me.  You are obviously employed by BlueRiver and have many more years of experience with Mura compared to me.

**Comment by stevewithington** [comment]
> ... my question is, how do I render the View inside of the Mura Theme? I wish to render the View inside of the Mura Theme by processing the Mura Theme inside of the Layout that the View is being rendered in. Does this clarify what I wish to do?

I'm sorry ... but I think I'm still confused. Maybe a visual would help?

Here's the thing, when you access `/plugins/myPlugin/index.cfm/app1:main` directly, you're technically accessing the display object itself. Are you saying you want Mura's "Admin" template to output around the display object output when accessing it directly?

**Comment by dbudde** [comment]
@stevewithington  I believe this is all just a misunderstanding on my part.  I was not following that (other than the admin section of the plugin) the sub systems were intended to be rendered as a display object you could place into your Mura pages.  I thought there was supposed to be the option to both use it as a display object and to go the the sub system directly using the URL.

My thought was, that if you went to the sub system directly through the URL, that there should be a way to render the (traditionally public side theme) Mura theme within the layout for the sub system.  Now that I understand that sub systems (other than the plugin's admins sub system) are intended to operate as a display object solely, it clears up a lot for me.

> Here's the thing, when you access /plugins/myPlugin/index.cfm/app1:main directly, you're technically accessing the display object itself.

Just to be clear, when you do access a sub system directly through the URL, you are not using the display object at all, correct?  This is just more for curiosity on my part.

@stevewithington  thanks for attempting to answer my questions.  I know with me coming at this from a different mindset can really throw off the understanding and make my questions sound like nonsense.

**Comment by stevewithington** [comment]
@dbudde please think of this plugin as a base/starter plugin, and feel free to modify it to suit your specific needs/use cases. Of course you can create and/or use as many subsystems as you wish, and choose _not_ to have them appear as display objects at all, and have users navigate directly to the subsystem itself. Or, even have a combination of variations of that available ... it's entirely up to you!

That said, if you expect users to visit the subsystem directly, please keep in mind that when they do, that the request is being funneled directly to your app, and it is **not** a front-end request to Mura. I want to make this abundantly clear, because based on your statement:

> My thought was, that if you went to the sub system directly through the URL, that there should be a way to render the (traditionally public side theme) Mura theme within the layout for the sub system. 

The `public side theme` for example, MuraBootstrap3, is only used in context of a front-end request. You could always create and/or copy the theme layout for your plugin and use it that way ... but to think that you can invoke some method in Mura to go grab the theme isn't the best way to approach this. Remember, the vast majority of themes have several layout options ... and most importantly, have display regions, as well as a **body** section, etc. 

To me, it sounds like you're wanting to use the main theme, (e.g., MuraBootstrap3), and render your application as the body section of the page. Again, if this is the case, you're thinking and approaching this completely wrong.

When you access the subsystem directly, you're using your app as its own isolated application ... it should function the same as it would as if it were being used as a display object that has been assigned to a specific display region on the front-end, public view of the site. You could throw in your own custom logic to see if the request is a true, Mura front-end request, and then if so, don't use any particular layout ... but if it's not a Mura front-end request, then use your own custom layout.

I certainly hope this answers your question/s and clears things up for you. If so, please close this ticket. Thanks!

**Comment by dbudde** [comment]
I think this is a lot clearer to me now.  Thanks.
